import React from "react";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });
import "./css/globals.css";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import customTheme from "@/utils/theme/custom-theme";
import { CustomizerContextProvider } from "@/app/context/CustomizerContext";
import { ApolloWrapper } from "@/app/components/ApolloWrapper";
import "../utils/i18n";
import NextTopLoader from "nextjs-toploader";
import { getServerSession } from "next-auth";
import SessionProviderWrapper from "@/app/components/nextauth/SessionProviderWrapper";
import { authOptions } from "@nextauth/app/api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Modernize - Nextjs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <ThemeModeScript />
      </head>
      <body className={`${plus_jakarta_sans.className}`}>
        <SessionProviderWrapper session={session}>
          <ApolloWrapper>
            <Flowbite theme={{ theme: customTheme }}>
              <CustomizerContextProvider>
                <NextTopLoader color="var(--color-primary)" />
                {children}
              </CustomizerContextProvider>
            </Flowbite>
          </ApolloWrapper>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
